---
title: "MarioKart Records"
author: "Adam Haertter & Brennan Mulligan"
format: pdf
---

The data here is based on the tidytuesday Dataset for [Mario Kart 64 World Records](https://github.com/rfordatascience/tidytuesday/tree/master/data/2021/2021-05-25). There are two different sources of data, being one for world records and one for the drivers, or players, associated with these records.


```{r}
library("tidyverse")
library("readr")
library("dplyr")
library("magrittr")
records <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-05-25/records.csv')
drivers <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-05-25/drivers.csv')
```

```{r}
# Compare the times of both systems played for each track
three_lap <- records %>% filter(type == "Three Lap") %>%
  group_by(track, system_played) %>%
  summarize(best_time = min(time))

ggplot(three_lap, aes(x = track, y = best_time, fill = system_played)) + geom_bar(stat = "identity", position = position_dodge()) + labs(x = "Tracks", y = "Times", title = "Three Lap") + theme(plot.title = element_text(hjust = 0.5),
        axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) + guides(fill = guide_legend(title = "System Played"))

single_lap <- records %>% filter(type == "Single Lap") %>%
  group_by(track, system_played) %>%
  summarize(best_time = min(time))

ggplot(single_lap, aes(x = track, y = best_time, fill = system_played)) + geom_bar(stat = "identity", position = position_dodge()) + labs(x = "Tracks", y = "Times", title = "Single Lap") + theme(plot.title = element_text(hjust = 0.5),
        axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) + guides(fill = guide_legend(title = "System Played"))
```

```{r}
# Which countries prefer which tracks?
driver_simple <- drivers %>% 
  group_by(player) %>% 
  .[, c(1,2,3,6)] %>% 
  unique()

driver_simple$nation <- as_factor(driver_simple$nation)

func <- function(x) return(mutate(x, num = count(x, nation)))

country <- records %>% left_join(driver_simple, by = "player") %>%
  .[, c(1,4,5,12)] 

country %<>%
  group_by(track, nation) %>% 
  summarize(count = n(), .groups = "drop") %>% 
  ungroup()


theme_set(theme_classic())
ggplot(country, aes(x = track, y = nation, fill = count)) +
  geom_tile() +
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) +
  scale_fill_gradient(low = "white", high = "darkgreen") +
  labs(x = "Track", 
       y = "Country", 
       fill = "# World Records", 
       title = "Heatmap of Most Contentious Mario Kart Track Records by Country")

```